api:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - 'api/**/*.go'

controller:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - 'controllers/*.go'

crd:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - 'config/crd/bases/*.yaml'

dependencies:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - 'go.mod'
      - 'go.sum'

documentation:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - 'charts/**/*.md'
      - 'docs/*.md'
    - all-globs-to-all-files:
      - '!CHANGELOG.md'

github_actions:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - '**/workflows/*.yaml'
      - '**/workflows/*.yml'

golang:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.go'

helm-chart:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - 'charts/**/*.yaml'

release:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - 'version/VERSION'

test:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_test.go'
