api:
- 'api/**/*.go'

controller:
- 'controllers/*.go'

crd:
- 'config/crd/bases/*.yaml'

documentation:
- 'README.md'
- 'docs/*.md'

github_actions:
- '**/workflows/*.yaml'
- '**/workflows/*.yml'

golang:
- '**/*.go'

helm-chart:
- 'charts/**/*.yaml'

test:
- '**/*_test.go'
