# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

api:
- api/**/*.go

helm-chart:
- charts/**/*.yaml

controller:
- controllers/*.go

crd:
- config/crd/bases/*.yaml

documentation:
- README.md
- docs/*.md

golang:
- '**/*.go'
