changesDir: .changes
unreleasedDir: unreleased
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} ({{.Time.Format "January 02, 2006"}})'
kindFormat: '{{.Kind}}:'
changeFormat: '* {{.Body}} [[GH-{{.Custom.PR}}](https://github.com/hashicorp/terraform-cloud-operator/pull/{{.Custom.PR}})]'
custom:
  - key: PR
    label: PR Number
    type: int
    minInt: 1
kinds:
  - label: BREAKING CHANGES
  - label: BUG FIXES
  - label: DEPENDENCIES
  - label: ENHANCEMENTS
  - label: FEATURES
  - label: NOTES
newlines:
  afterKind: 1
  beforeKind: 1
  endOfVersion: 2
