changesDir: .changes
unreleasedDir: unreleased
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} ({{.Time.Format "January 02, 2006"}})'
fragmentFileFormat: '{{.Kind}}-{{.Custom.PR}}-{{.Time.Format "20060102-150405"}}'
kindFormat: '{{.Kind}}:'
changeFormat: '* {{.Body}} [[GH-{{.Custom.PR}}](https://github.com/hashicorp/hcp-terraform-operator/pull/{{.Custom.PR}})]'
custom:
  - key: PR
    label: PR Number
    type: int
    minInt: 1
kinds:
  - label: BREAKING CHANGES
    auto: minor
  - label: NOTES
    auto: minor
  - label: BUG FIXES
    auto: patch
  - label: FEATURES
    auto: minor
  - label: ENHANCEMENTS
    auto: minor
  - label: DEPENDENCIES
    auto: minor
newlines:
  afterKind: 1
  beforeKind: 1
  endOfVersion: 2
