# Copyright IBM Corp. 2022, 2025
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: this
spec:
  organization: kubernetes-operator
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  name: kubernetes-operator-demo
  project:
    name: kubernetes-operator
    # Alternatively, you can use the Project ID:
    #
    # id: prj-e89jyCXbxi1sU2AR
