---
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: this
spec:
  organization: kubernetes-operator
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  name: kubernetes-operator-demo
  variablesets: 
    - varSetName: "testing"
    #Alternatively, you can use the Variable Set ID
    #
    #varSetID: "varset-hLdht7LL9mdV4MYD"