# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# -- Reference to one or more secrets essential for pulling container images.
imagePullSecrets: []

# -- Additional labels to add to the Operator pods.
podLabels: {}

# -- The number of Operator replicas.
replicaCount: 2

# -- Deployment pod security context. More information in [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
securityContext:
  runAsNonRoot: true

# -- Deployment priorityClassName. More information in [Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/).
priorityClassName: ""

# Operator-global options.
operator:
  image:
    # -- Image repository.
    repository: hashicorp/hcp-terraform-operator
    # -- Image pull policy.
    pullPolicy: IfNotPresent
    # -- Image tag. Defaults to `.Chart.AppVersion`.
    tag: ""
  resources:
    limits:
      # -- Limits as a maximum amount of CPU to be used by a container.
      cpu: 500m
      # -- Limits as a maximum amount of memory to be used by a container.
      memory: 128Mi
    requests:
      # -- Guaranteed minimum amount of CPU to be used by a container.
      cpu: 50m
      # -- Guaranteed minimum amount of memory to be used by a container.
      memory: 64Mi

  # -- Container security context. More information in [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  # Usage example:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: kubernetes.io/arch
  #           operator: In
  #           values:
  #           - amd64
  #
  # -- Kubernetes Affinity. More information: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  # Usage example:
  # tolerations:
  # - key: "kubernetes.azure.com/scalesetpriority"
  #   operator: "Equal"
  #   value: "spot"
  #   effect: "NoSchedule"
  #
  # -- Kubernetes Tolerations. More information: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []

  # -- The minimum frequency at which watched resources are reconciled. Format: `5s`, `1m`, etc.
  syncPeriod: 1h

  # -- List of namespaces the controllers should watch.
  watchedNamespaces: []

  # -- The API URL of a Terraform Enterprise instance.
  tfeAddress: ""

  # -- Whether or not to ignore TLS certification warnings.
  skipTLSVerify: false

kubeRbacProxy:
  image:
    # -- Image repository.
    repository: quay.io/brancz/kube-rbac-proxy
    # -- Image pull policy.
    pullPolicy: IfNotPresent
    # -- Image tag.
    tag: v0.18.2

  # -- Container security context. More information in [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  resources:
    limits:
      # -- Limits as a maximum amount of CPU to be used by a container.
      cpu: 500m
      # -- Limits as a maximum amount of memory to be used by a container.
      memory: 128Mi
    requests:
      # -- Guaranteed minimum amount of CPU to be used by a container.
      cpu: 50m
      # -- Guaranteed minimum amount of memory to be used by a container.
      memory: 64Mi

# Controllers-specific options.
controllers:
  agentPool:
    # --  The number of the Agent Pool controller workers.
    workers: 1
    # -- The minimum frequency at which watched Agent Pool resources are reconciled. Format: 5s, 1m, etc.
    syncPeriod: 30s
  module:
    # -- The number of the Module controller workers.
    workers: 1
    # -- The minimum frequency at which watched Module resources are reconciled. Format: 5s, 1m, etc.
    syncPeriod: 5m
  project:
    # -- The number of the Project controller workers.
    workers: 1
    # -- The minimum frequency at which watched Project resources are reconciled. Format: 5s, 1m, etc.
    syncPeriod: 5m
  workspace:
    # -- The number of the Workspace controller workers.
    workers: 1
    # -- The minimum frequency at which watched Workspace resources are reconciled. Format: 5s, 1m, etc.
    syncPeriod: 5m

# -- The base64 encoded custom Certificate Authority bundle used to validate API TLS certificates.
customCAcertificates: ""

serviceAccount:
  # -- Specifies whether a ServiceAccount should be created.
  create: true
  # -- Additional annotations for the ServiceAccount.
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

rbac:
  # -- Specifies whether a Role-Based Access Control (RBAC) resources should be created.
  create: true
