apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: hcp-terraform-operator
  name: leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hcp-terraform-operator-leader-election
subjects:
- kind: ServiceAccount
  name: hcp-terraform-operator-manager
  namespace: system
