# permissions for end users to edit projects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: project-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: terraform-cloud-operator
    app.kubernetes.io/part-of: terraform-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-editor-role
rules:
- apiGroups:
  - app.terraform.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - projects/status
  verbs:
  - get
