---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - modules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - modules/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - modules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
