---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hcp-terraform-operator
  name: manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools
  - modules
  - projects
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools/finalizers
  - modules/finalizers
  - projects/finalizers
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools/status
  - modules/status
  - projects/status
  - workspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
