{{- if .Values.rbac.create -}}
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - list
  - update
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools
  - agenttokens
  - modules
  - projects
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools/finalizers
  - agenttokens/finalizers
  - modules/finalizers
  - projects/finalizers
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools/status
  - agenttokens/status
  - modules/status
  - projects/status
  - workspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end -}}
