// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/controller/agentpool_controller_autoscaling.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAgentPoolControllerAutoscaling is a mock of AgentPoolControllerAutoscaling interface.
type MockAgentPoolControllerAutoscaling struct {
	ctrl     *gomock.Controller
	recorder *MockAgentPoolControllerAutoscalingMockRecorder
}

// MockAgentPoolControllerAutoscalingMockRecorder is the mock recorder for MockAgentPoolControllerAutoscaling.
type MockAgentPoolControllerAutoscalingMockRecorder struct {
	mock *MockAgentPoolControllerAutoscaling
}

// NewMockAgentPoolControllerAutoscaling creates a new mock instance.
func NewMockAgentPoolControllerAutoscaling(ctrl *gomock.Controller) *MockAgentPoolControllerAutoscaling {
	mock := &MockAgentPoolControllerAutoscaling{ctrl: ctrl}
	mock.recorder = &MockAgentPoolControllerAutoscalingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentPoolControllerAutoscaling) EXPECT() *MockAgentPoolControllerAutoscalingMockRecorder {
	return m.recorder
}

// pendingWorkspaceRuns mocks base method.
func (m *MockAgentPoolControllerAutoscaling) pendingWorkspaceRuns(ctx context.Context) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "pendingWorkspaceRuns", ctx)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// pendingWorkspaceRuns indicates an expected call of pendingWorkspaceRuns.
func (mr *MockAgentPoolControllerAutoscalingMockRecorder) pendingWorkspaceRuns(ctx, ap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "pendingWorkspaceRuns", reflect.TypeOf((*MockAgentPoolControllerAutoscaling)(nil).pendingWorkspaceRuns), ctx, ap)
}
