apiVersion: app.terraform.io/v1alpha2
kind: Project
metadata:
  name: <NAME>
spec:
  organization: <ORG_NAME>
  token:
    secretKeyRef:
      name: <SECRET_NAME>
      key: <SECRET_KEY>
  name: <NAME>
