apiVersion: app.terraform.io/v1alpha2
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: project
    app.kubernetes.io/instance: project-sample
    app.kubernetes.io/part-of: terraform-cloud-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: terraform-cloud-operator
  name: project-sample
spec:
  # TODO(user): Add fields here
