apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: <NAME>
spec:
  organization: <ORG_NAME>
  token:
    secretKeyRef:
      name: <SECRET_NAME>
      key: <SECRET_KEY>
  module:
    source: redeux/terraform-cloud-agent/kubernetes
    version: 1.0.1
  workspace:
    id: <WORKSPACE_ID>
