apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: this
spec:
  organization: kubernetes-operator
  token:
    secretKeyRef:
      name: hcp-terraform-operator
      key: token
  module:
    source: redeux/terraform-cloud-agent/kubernetes
    version: 1.0.1
  workspace:
    id: ws-NUVHA9feCXzAmPHx
