{{- if .Values.customCAcertificates -}}
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ca-certificates
  namespace: {{ .Release.Namespace }}
data:
  ca-certificates: |-
{{ .Files.Get .Values.customCAcertificates | indent 4 }}

{{- end }}