# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - modules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - modules/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - modules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
