apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: {{ .Release.Name }}-controller-manager
  name: {{ .Release.Name }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: {{ .Release.Name }}-controller-manager
