name: Scan Docker image for vulnerabilities

on:
  schedule:
    - cron: '30 7 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker image metadata
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e # v4.4.0
        with:
          images: operator
          tags: |
            type=sha,format=long

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0
        with:
          platforms: amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0

      - name: Build and load Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          platforms: linux/amd64
          push: false
          load: true
          build-args:
            BIN_NAME=${{ vars.BIN_NAME }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@e5f43133f6e8736992c9f3c1b3296e24b37e17f2 # 0.10.0
        with:
          scan-type: image
          format: sarif
          image-ref: ${{ steps.meta.outputs.tags }}
          output: 'trivy-results.sarif'
          exit-code: '1'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@f31a31c052207cc13b328d6295c5b728bb49568c # codeql-bundle-20230428
        with:
          category: 'Trivy Security Scan'
          sarif_file: 'trivy-results.sarif'
