name: E2E on Terraform Enterprise

on:
  schedule:
    - cron: '30 5 * * *'
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: 'go.mod'

      - name: Run end-to-end test suite
        run: make test
        env:
          TFC_OAUTH_TOKEN: ${{ secrets.TFE_OAUTH_TOKEN }}
          TFC_ORG: ${{ secrets.TFE_ORG }}
          TFC_TOKEN: ${{ secrets.TFE_TOKEN }}
          TFC_VCS_REPO: ${{ secrets.TFE_VCS_REPO }}
          TFE_ADDRESS: ${{ secrets.TFE_ADDRESS }}
