name: Helm Chart Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - 'charts/hcp-terraform-operator/**'
      - 'version/VERSION'
  workflow_dispatch:

env:
  HELM_CHART_PATH: 'charts/hcp-terraform-operator'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: Azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: v3.11.2

      - name: Set up Helm Plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run unit tests suite
        run: |
          helm unittest ${{ env.HELM_CHART_PATH }}
