name: Helm Chart Unit Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
      - 'version/VERSION'
  push:
    branches:
      - main
  workflow_dispatch:

env:
  HELM_CHART_PATH: 'charts/hcp-terraform-operator'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'

      - name: Set up Helm
        uses: Azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: v3.11.2

      - name: Run unit tests suite [Go]
        run: |
          make helm-test
