name: Check Markdown links

on:
  schedule:
    - cron: '30 4 * * *'
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0

      - name: Run Markdown links checker
        uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1.0.14
        with:
          use-quiet-mode: yes
          use-verbose-mode: yes
          folder-path: './, ./docs'
          max-depth: 0
          base-branch: main
