name: Tag Release

on:
  push:
    branches:
      - main
    paths:
      - version/VERSION

env:
  TAG: v$(cat version/VERSION)

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Create tag
        run: |
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
