name: Tag Release

on:
  push:
    branches:
      - main
    paths:
      - version/VERSION

env:
  TAG: v$(cat version/VERSION)

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Create tag
        run: |
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
